require_relative '../nyc_pigeon_organizer'
def pigeonsorter(hash)
#make new hash
newHash = {}
hash.each do |cgl,blockofgarbage|
  blockofgarbage.each do |garbagespecific,names|
     names.each do |pigeon_name|
        if newHash[pigeon_name] == nil
          newHash[pigeon_name] = {}
        end
        if newHash[pigeon_name][cgl] == nil
           newHash[pigeon_name][cgl] = []
        end
          newHash[pigeon_name][cgl].push(garbagespecific.to_s)

     end
  end
end
return newHash
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # config here
end
